services:
  auth-db:
    image: postgres:16.2
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - worklink_network
    volumes:
      - auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  core-db:
    image: postgres:16.2
    container_name: core-db
    restart: always
    environment:
      POSTGRES_DB: core_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    networks:
      - worklink_network
    volumes:
      - core_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d core_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  payment-db:
    image: postgres:16.2
    container_name: payment-db
    restart: always
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    networks:
      - worklink_network
    volumes:
      - payment_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  contract-db:
      image: postgres:16.2
      container_name: contract-db
      restart: always
      environment:
        POSTGRES_DB: contract_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5437:5432"
      networks:
        - worklink_network
      volumes:
        - contract_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d payment_db"]
        interval: 5s
        timeout: 5s
        retries: 10

volumes:
  auth_data:
  core_data:
  payment_data:
  contract_data:

networks:
  worklink_network:
    driver: bridge
