services:
  auth-db:
    image: postgres:16.2
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - worklink_network
    volumes:
      - auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  core-db:
    image: postgres:16.2
    container_name: core-db
    restart: always
    environment:
      POSTGRES_DB: core_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    networks:
      - worklink_network
    volumes:
      - core_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d core_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  payment-db:
    image: postgres:16.2
    container_name: payment-db
    restart: always
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      FRONTEND_URL: http://localhost:5173
    ports:
      - "5436:5432"
    networks:
      - worklink_network
    volumes:
      - payment_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  contract-db:
      image: postgres:16.2
      container_name: contract-db
      restart: always
      environment:
        POSTGRES_DB: contract_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5437:5432"
      networks:
        - worklink_network
      volumes:
        - contract_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d contract_db"]
        interval: 5s
        timeout: 5s
        retries: 10

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./auth-service/.env
    environment:
      AUTH_DB: postgresql+psycopg2://postgres:postgres@auth-db:5432/auth_db
      CORE_SERVICE_URL: http://core-service:8001
      BACKEND_URL: http://localhost:8000
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - worklink_network

  core-service:
    build:
      context: ./core-service
    container_name: core-service
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - ./core-service/.env
    environment:
      CORE_DB: postgresql+psycopg2://postgres:postgres@core-db:5432/core_db
      CONTRACT_SERVICE_URL: http://contract-service:8002
      PAYMENT_SERVICE_URL: http://payment-service:8003
    depends_on:
      core-db:
        condition: service_healthy
    networks:
      - worklink_network

  contract-service:
    build:
      context: ./contract-service
    container_name: contract-service
    ports:
      - "8002:8002"
    env_file:
      - ./contract-service/.env
    environment:
      CONTRACT_DB: postgresql+psycopg2://postgres:postgres@contract-db:5432/contract_db
      CORE_SERVICE_URL: http://core-service:8001
    depends_on:
      contract-db:
        condition: service_healthy
    networks:
      - worklink_network

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    restart: always
    ports:
      - "8003:8003"
    env_file:
      - ./payment-service/.env
    environment:
      PAYMENT_DB: postgresql+psycopg2://postgres:postgres@payment-db:5432/payment_db
      CORE_SERVICE_URL: http://core-service:8001
      CONTRACT_SERVICE_URL: http://contract-service:8002
    depends_on:
      payment-db:
        condition: service_healthy
    networks:
      - worklink_network

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    restart: unless-stopped
    env_file:
      - ./payment-service/.env
    command:
      - listen
      - --forward-to
      - http://payment-service:8003/payments/webhooks/stripe
      - --forward-connect-to
      - http://payment-service:8003/payments/webhooks/stripe
    depends_on:
      - payment-service
    networks:
      - worklink_network

volumes:
  auth_data:
  core_data:
  payment_data:
  contract_data:

networks:
  worklink_network:
    driver: bridge
